//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace logindn
{
    using System;
    using System.Collections.Generic;
    
    public partial class GheNgoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GheNgoi()
        {
            this.Ves = new HashSet<Ve>();
        }
    
        public string idGheNgoi { get; set; }
        public Nullable<bool> p1 { get; set; }
        public Nullable<bool> p2 { get; set; }
        public Nullable<bool> p3 { get; set; }
        public Nullable<bool> p4 { get; set; }
        public Nullable<bool> p5 { get; set; }
        public Nullable<bool> p6 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ve> Ves { get; set; }
    }
}
